# Big Data algoritmusok és programozás - Python

# 2. gyakorlat

## NumPy

___
NumPy (numpy) - a Python lineáris algebra könyvtára. Azért fontos data science területén, mert szinte minden könyvtára használja a NumPy fő elemeit.

Dokumentáció: [NumPy Manual](https://numpy.org/doc/stable/)

A Numpy nagyon gyors, mivel C könyvtárakhoz kapcsolódik.

A gyakorlaton: a NumPy alapok megtanulása.


_____
### Installálás (amennyiben szükéges)

Anaconda környezetben, NumPy installálása terminál ablakban:
    
    conda install numpy
    
vagy nem Anaconda környezetben:

    pip install numpy
    
Bővebben a telepítésről: [Numpy hivatalos dokumentációja a telepítésről.](https://numpy.org/install/)

___
## NumPy használata

Telepítés után a könyvtár importálása:

In [2]:
import numpy as np

_____
# Numpy tömbök (Numpy Arrays)

A NumPy tömbök többfélék lehetnek: vektorok (1-D tömb), mátrixok (2-D tömb) és 3 vagy többdimenziós tömbök.

Az 1-D tömbök esetén nincs különbség a sorvektor és az oszlopvektor között.

## NumPy tömbök létrehozása

### Python listából

Tömbök készítése közvetlenül listák vagy listákból álló listák átalakításával:

In [3]:
lista = [1,2,3]
lista

[1, 2, 3]

In [4]:
# np.array()
np.array(lista)

array([1, 2, 3])

In [5]:
print(lista)
print(np.array(lista))

[1, 2, 3]
[1 2 3]


In [6]:
lista_lista = [[1,2,3],[4,5,6],[7,8,9]]
lista_lista

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(lista_lista)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# np.mat()
mátrix = np.matrix('1 2 3; 4 5 6; 7 8 9')
mátrix

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [9]:
sokszínű_lista = [1, 'a', 1.1, "xyzaaaaaaaaaaaaaaa"]

In [10]:
# A tömb elemei azonos típusúak (array dtype).
sokszínű = np.array(sokszínű_lista)
sokszínű

array(['1', 'a', '1.1', 'xyzaaaaaaaaaaaaaaa'], dtype='<U32')

## Beépített módszerek numpy tömbök létrehozására

Sokféleképpen generálhatunk tömböt.

### arange

Egyenletesen elosztott értékek megadása egy adott intervallumon belül.

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# tömb létrehozása 2 és 10 között minden 2. elemmel


### zeros, ones

Tömbök generálása 0 - `np.zeros()` vagy 1 - `np.ones()` elemekkel.

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
# tömb elemei legyenek egész számok


In [16]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
# tömb legyen (2,3,4) dimenziós és elemei egész számok


# empty

Üres tömb létrehozása. Az `empty` függvény létrehoz egy tömböt, amelynek kezdeti tartalma véletlenszerű, a memória állapotától függ. Az `empty` használatának (`zeros` helyett) jelentősége a sebesség - később nem szabad elfeledkezni az összes konkrét elem feltöltéséről!

In [19]:
üres = np.empty((2,2))
üres

array([[4.67685077e-310, 0.00000000e+000],
       [4.67576417e-310, 4.67576420e-310]])

Kódrészletek végrehajtási idejének mérése: `timeit`
https://docs.python.org/3/library/timeit.html

In [20]:
import timeit
print("zeros: ",timeit.timeit("numpy.zeros((100,100))",setup="import numpy"))
print("empty: ",timeit.timeit("numpy.empty((100,100))",setup="import numpy"))

zeros:  2.2135732540045865
empty:  0.42723444400326116


### linspace

Egyenletesen elosztott számok megadása egy meghatározott intervallumon belül.

In [21]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [22]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
# 10 és 100 között 10 szám kiírása, egész számokkal


### eye

Egységmátrix készítése.

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Készítsük el a következő mátrixot az `eye` függvény segítségével:
```python
array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])
```

In [26]:
np.eye(4,4,k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

_____
## Véletlen számokból álló tömbök

A Numpy-ban sokféle lehetőség van véletlen tömbök készítésére:

### rand
Létrehoz egy megadott méretű tömböt és ``[0, 1)`` feletti egyenletes eloszlás szerinti véletlen értékekkel feltölti.

In [35]:
np.random.rand(2)

array([0.05389091, 0.58498082])

In [28]:
np.random.rand(5,5)

array([[0.34289898, 0.75056483, 0.00650489, 0.28657541, 0.75466241],
       [0.85025779, 0.70954562, 0.17765077, 0.27791535, 0.94663429],
       [0.53499247, 0.30753315, 0.58992445, 0.64538932, 0.49411877],
       [0.36257936, 0.94423722, 0.19520955, 0.84956101, 0.03277736],
       [0.51206969, 0.07918477, 0.67648806, 0.41037732, 0.39198942]])

### randn

Standard normál eloszlás szerinti értékekkel tölti fel a tömböt.

In [40]:
np.random.randn(2)

array([ 1.0923829 , -0.06569029])

In [41]:
np.random.randn(5,5)

array([[-0.36320311, -0.27107879, -0.76046046, -2.57444408,  0.23458577],
       [ 1.09330939, -0.9909884 , -0.42299501,  1.32325855, -0.30131518],
       [-0.91564675,  0.54570217,  0.27236425,  0.22894394, -1.0053804 ],
       [ 1.8759971 ,  0.57929954, -2.03836163,  0.69912994,  0.43512941],
       [-0.45942706,  0.76225461, -0.14919645, -0.3361843 , -0.37587688]])

### randint
Véletlen egész értékekkel tér vissza `low` (inclusive) és `high` (exclusive) intervallumból.

In [42]:
np.random.randint(1,100)

54

In [43]:
np.random.randint(1,100,10)

array([92, 49, 64, 78, 31, 46, 35, 98, 66, 29])

In [44]:
np.random.randint(1,100,(10,10))

array([[93, 30, 92, 73, 50, 69, 29, 11, 25, 14],
       [59, 48, 11,  1, 24, 16, 56, 51, 83, 40],
       [11, 93, 18, 36, 35, 20,  4, 91, 97, 55],
       [82, 53,  1, 27, 90, 34, 84, 57, 53, 26],
       [ 7, 55, 49, 67, 11, 89, 63, 87, 30, 96],
       [98, 11, 77, 82, 32, 96,  3, 11, 41, 61],
       [21, 37, 45, 33, 42, 18, 70, 99, 87, 76],
       [41, 41, 28, 96, 90, 46, 15, 60, 11, 78],
       [ 8, 46, 90, 53, 73, 66, 96,  4, 75, 61],
       [77, 68, 34, 81, 88, 13, 49, 31,  8, 81]])

_____
## Tömb elemeinek rendezése, hozzáadása, törlése

### sort

In [45]:
rendezetlen = np.random.randint(1,100,10)
rendezetlen

array([82, 71, 68,  3, 35, 20, 20, 27, 55, 30])

In [46]:
rendezett = np.sort(rendezetlen)
rendezett

array([ 3, 20, 20, 27, 30, 35, 55, 68, 71, 82])

### concatenate

In [47]:
np.concatenate(([1,2],[3,4,5]))

array([1, 2, 3, 4, 5])

In [48]:
a = np.array([[5, 10],[15, 20]])
b = np.array([[25, 30]])
print(a,'\n')
print(b)

[[ 5 10]
 [15 20]] 

[[25 30]]


In [49]:
np.concatenate((a,b))

array([[ 5, 10],
       [15, 20],
       [25, 30]])

Fűzzük össze az `a` és `b` tömböket, hogy az eredmény
```python
array([[ 5, 10, 25],
       [15, 20, 30]])
```
legyen!

In [52]:
np.concatenate(a[0][0],a[0][1],b[0][0])

TypeError: 'numpy.int64' object is not iterable

In [53]:
np.concatenate((a,b), axis=0)

array([[ 5, 10],
       [15, 20],
       [25, 30]])

In [54]:
np.concatenate((a,b),axis=None)

array([ 5, 10, 15, 20, 25, 30])

### insert
Értékek elhelyezése az adott tengely mentén a megadott indexek elé.

In [55]:
a

array([[ 5, 10],
       [15, 20]])

In [56]:
np.insert(a,1,100)

array([  5, 100,  10,  15,  20])

In [57]:
np.insert(a,1,100,axis=0)

array([[  5,  10],
       [100, 100],
       [ 15,  20]])

In [58]:
np.insert(a,1,100,axis=1)

array([[  5, 100,  10],
       [ 15, 100,  20]])

Szúrjuk be az `a` tömb elejére és végére a `100, 200` elemekből álló oszlopvektort.

In [59]:
np.insert(a,-1,(100,200),axis=1)

array([[  5, 100,  10],
       [ 15, 200,  20]])

In [60]:
np.insert(a,1,[[100,200],[300,400]],axis=1)

array([[  5, 100, 300,  10],
       [ 15, 200, 400,  20]])

### Eltávolítás
Az elemek tömbből való eltávolításának egyszerű módja a megtartandó elemek indexeléssel történő kiválasztása. (Később)

_____
## Tömbfüggvények

In [61]:
arr = np.arange(20)
ranarr = np.random.randint(0,50,10)

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [65]:
ranarr

array([15, 22, 16, 33, 27, 14, 37,  9, 18, 39])

### reshape
Egy tömböt ad vissza, amely ugyanazokat az adatokat tartalmazza, új alakban.

In [68]:
np.reshape(arr,(20,1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [67]:
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### max, min, argmax, argmin

Hasznos módszerek a maximum vagy a minimum értékek megállapításához, továbbá megtalálni az index értékét az `argmin` vagy az `argmax` segítségével.

In [ ]:
ranarr

In [ ]:
ranarr.max()

In [ ]:
ranarr.argmax()

In [ ]:
ranarr.min()

In [ ]:
ranarr.argmin()

## Tömb attribútumok
### shape

A tömb alakja (shape) egész számokból álló értéksor (tuple), amely megadja a tömb méretét az egyes dimenziók mentén.

In [ ]:
arr

In [ ]:
# 1-D
arr.shape

In [ ]:
np.shape(arr)

In [ ]:
# Megjegyzés: 2-D, dupla zárójel [[]]
arr.reshape(1,20)

In [ ]:
arr.reshape(1,20).shape

In [ ]:
arr.reshape(20,1)

In [ ]:
arr.reshape(20,1).shape

### ndim
A tömb dimenzióinak száma, a tömb rangja.

In [ ]:
arr.ndim

In [ ]:
arr.reshape(1,20).ndim

In [ ]:
np.ones((2,2,2,2)).ndim

### size
A tömb elemeinek száma.

In [ ]:
np.ones((2,2,2,2)).size

### dtype
A tömb elemeinek típusa (mindegyik elem azonos típusú).

In [ ]:
arr.dtype

In [ ]:
sokszínű.dtype

További információk: [Array attributes](https://numpy.org/doc/stable/reference/arrays.ndarray.html#array-attributes)

___
## NumPy indexelés és kiválasztás

Elemek vagy elemek csoportjának kiválasztása egy tömbből.

In [ ]:
#Tömb (vektor) készítése
vektor = np.arange(0,11)

In [ ]:
#Tömb megjelenítése
vektor

### Zárójeles indexelés és kiválasztás
A tömb egyik vagy néhány elemének kiválasztásának legegyszerűbb módja. Nagyon hasonlít a Python listákhoz.

In [ ]:
#Egy adott indexhez tartozó érték elérése
vektor[5]

In [ ]:
#Egy indextartományhoz tartozó értékek elérése
#[start:stop]
vektor[1:6]

In [ ]:
vektor[0:5]

In [ ]:
vektor[2:]

In [ ]:
vektor[:5]

In [ ]:
vektor[-3:-1]

In [ ]:
#[start:stop:step]
vektor[1:6:2]

In [ ]:
vektor[2::2]

In [ ]:
# vektor elemeinek megjelenítése fordított sorrendben

### 2D tömbök (mátrixok) indexelése

Általános formátum: **`arr_2d[sor][oszlop]`** vagy **`arr_2d[sor,oszlop]`**.

In [ ]:
#Mátrix készítése
mátrix = np.array(([5,10,15],[20,25,30],[35,40,45]))

#A tömb megjelenítése
mátrix

In [ ]:
#Indexelés
mátrix[1]

In [ ]:
# Egyedi elem értékének meghatározása
mátrix[1][0]

In [ ]:
# 3. sor 2. elemének kiválasztása


In [ ]:
#Legalsó sor kiválasztása


In [ ]:
mátrix[2,:]

In [ ]:
#Középső oszlop kiválasztása


In [ ]:
# 2D tömb szeletelése (résztömb kiválasztása)

#A jobb felső sarokban levő 2x2-es mátrix kiválasztása
mátrix[:2,1:]

In [ ]:
#A bal alsó sarokban levő 2x2-es mátrix kiválasztása


In [ ]:
mat = np.arange(50).reshape(5,10)

In [ ]:
mat

Válasszuk ki a `mat` mátrixból az alábbi résztömböt:
```python
array([[24, 25, 26],
       [34, 35, 36],
       [44, 45, 46]])
```

Válasszuk ki a `mat` mátrixból az alábbi résztömböt:
```python
array([[ 0,  2,  4,  6,  8],
       [20, 22, 24, 26, 28],
       [40, 42, 44, 46, 48]])
```

### Feltételes kiválasztás

In [ ]:
tömb = np.arange(1,11)
tömb

In [ ]:
tömb > 4

In [ ]:
bool_tömb = tömb>4

In [ ]:
bool_tömb

In [ ]:
tömb[bool_tömb]

In [ ]:
tömb[tömb>4]

In [ ]:
# A tömb páros elemeinek kiválasztása


In [ ]:
x = 2
tömb[tömb>x]

In [ ]:
tömb[(tömb < x) | (tömb > 3*x)]

In [ ]:
# A tömb x-nél nagyobb és 3x-nél kisebb elemeinek kiválasztása


___
## NumPy műveletek

### Aritmetikai műveletek


In [ ]:
tömb = np.arange(0,10)

In [ ]:
tömb

In [ ]:
tömb + tömb

In [ ]:
tömb - tömb

In [ ]:
tömb * tömb

In [ ]:
tömb + 100

In [ ]:
tömb * 100

In [ ]:
tömb**2

In [ ]:
# Tömb értékének nullával való osztása. Warning és nem hiba!!
# Érték helyettesítése: nan

tömb/tömb

In [ ]:
1/0

In [ ]:
tömb/0

In [ ]:
# Nullával való osztás. Warning és nem hiba!!
# Érték helyettesítése: inf

1/tömb

### Univerzális függvények

A Numpy számos univerzális függvénnyel rendelkezik: [universal array functions](https://numpy.org/doc/stable/reference/ufuncs.html).

Néhány ezek közül:

In [ ]:
#Négyzetgyökvonás
np.sqrt(tömb)

In [ ]:
#Exponenciális számítás
np.exp(tömb)

In [ ]:
#Maximum érték meghatározása
np.max(tömb) #azonos mint tömb.max()

In [ ]:
np.sin(tömb)

In [ ]:
np.log(tömb)

## Numpy objektumok mentése és beolvasása

In [ ]:
mátrix

In [ ]:
# Mentés 'xxx.npy' néven
np.save('xxx',mátrix)

In [ ]:
# Beolvasás .npy fájlból
npy = np.load('xxx.npy')

In [ ]:
npy

In [ ]:
# Mentés .csv fájlként
np.savetxt('xxx.csv', mátrix)

In [ ]:
# Beolvasás .csv fájlból
csv = np.loadtxt('xxx.csv')

In [ ]:
csv

## Numpy tömbön és Listán végzett műveletek sebességének összehasonlítása

In [ ]:
lista = list(np.random.randint(0, 1000, 10000000))
tömb = np.array(lista)

In [ ]:
import time
# Lista elemeinek négyzete
start = time.time()
lista_négyzet = [elem**2 for elem in lista]
end = time.time()
lista_idő = end - start
print(lista_idő)

# Tömb elemeinek négyzete

start = time.time()
tömb_négyzet = tömb ** 2
end = time.time()
tömb_idő = end - start
print(tömb_idő)

In [ ]:
arány = lista_idő / tömb_idő
print(arány)

---
---
***Feladat: BMI index meghatározása***

Az adatok:
|Név    |Kor    |Súly  |Magasság |
|-------|-------|------|---------|
|Anna   |34     |66    |1.65     |
|Zsófia |25     |55    |1.64     |
|János  |30     |86    |1.82     |
|Péter  |32     |76    |1.70     |
|Pál    |20     |68    |1.65     |
|Júlia  |28     |58    |1.70     |

- Készítsen numpy tömböt az adatokkal, majd írassa ki a tömböt.

- Válassza ki a súly oszlopot (index alapján), majd írassa ki az értékeket.

- Válassza ki a magasság oszlopot, majd írassa ki az értékeket.

- Számolja ki a BMI értékeket: BMI = súly / magasság<sup>2</sup>, majd írassa ki 2 tizedesjegyig.

Dokumentáció
- Numpy adattípusok és konverzió: https://numpy.org/doc/stable/user/basics.types.html
- Struktúrált tömbök: https://numpy.org/doc/stable/user/basics.rec.html